### ISSUE TITLE
ThumbnailToolbarButton does not appear after explorer.exe restart.

### ISSUE THREAD

**Issue by f-ever** [alexmercerind/windows_taskbar#8]
ThumbnailToolbarButton does not appear after explorer.exe restart.
```
Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.22579.100], locale zh-CN)
windows_taskbar: ^1.1.0+1
```

**Comment by alexmercerind** [comment]
Should I you report it to me or Microsoft?

**Comment by f-ever** [comment]
> Should you report it to me or Microsoft?

Other applications that use this feature do not have similar problems.

**Comment by alexmercerind** [comment]
> > Should you report it to me or Microsoft?
> 
> Other applications that use this feature do not have similar problems.

Examples...

**Comment by f-ever** [comment]
> > > Should you report it to me or Microsoft?
> > 
> > 
> > Other applications that use this feature do not have similar problems.
> 
> Examples...

iTunes, PotPlayer

**Comment by alexmercerind** [comment]
electron.js has same behavior. Feel free to raise the pull request implementing required behavior.

**Comment by f-ever** [comment]
Problem solved, I remove windows_taskbar from pubspec.yaml, this lib doesn't work in many cases, so it might be better to remove it.

**Comment by alexmercerind** [comment]
An open-source project published openly expects community fixes & not just reports.
It simply exposes [ITaskbarList3](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nn-shobjidl_core-itaskbarlist3) interface to Flutter & it is the intended behavior.

Either-way this plugin was made for my personal projects/applications (where it's working greatly) & decided to share it publicly here for no reason, **not for completing anyone's job or duty**.

I, as owner of this codebase, don't earn any profit, money, a single penny or reward by replying in these issue threads or even sharing this publicly.
`windows_taskbar` is published under MIT license, and comes with [NO WARRANTY](https://github.com/alexmercerind/windows_taskbar/blob/75d9a986ba8f2810e33a78db77438434356b2f4e/LICENSE#L15), don't blame it if you didn't pay for it. Contributing however, will ensure that you support the project's growth/stability (because it helped you implement a feature in your production app) & help future users of library aswell by being part of it. Thus, it's NOT my responsibility to fix these issues, but everyone using it.

Why would I care anyway? Don't use my code & waste your 3-5 hours writing from scratch.  ;)

Mind reading the full-license paragraph before using `windows_taskbar` in your app, [here](https://github.com/alexmercerind/windows_taskbar/blob/75d9a986ba8f2810e33a78db77438434356b2f4e/LICENSE#L15-L21).
Thanks. Have a great day.
